FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD csa-conference-1.0.0-SNAPSHOT.jar csa-twitter-search.jar
RUN sh -c 'touch /csa-twitter-search.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /csa-twitter-search.jar" ]